### Inserer les routes ici ###
#### SITE BUNDLE #####

Home:
    method: GET
    url: /
    bundle: frontend
    controller: HomeController
    action: index

ArticlesList:
    method: GET
    url: /blog/article/all
    bundle: frontend
    controller: HomeController
    action: index

### ACTIONS CONTROLLER ######
SendMessContact:
    method: POST
    url: /contact/sendMailContact
    bundle: frontend
    controller: HomeController
    action: sendMailContact

NewUserRegister:
    method: POST
    url: /user/new
    bundle: frontend
    controller: ActionsController
    action: registerUser

test:
    method: GET
    url: /home/index/{article_id}/{annee}
    bundle: frontend
    controller: HomeController
    action: index