### Inserer les routes ici ###
#### SITE BUNDLE #####

### HOME CONTROLLER ######
Home:
    method: GET
    url: /
    bundle: frontend
    controller: HomeController
    action: index

### USER CONTROLLER ######
MyAccount:
    method: GET
    url: /user/my-account
    bundle: frontend
    controller: UserController
    action: myAccount

### ACTIONS CONTROLLER ######
SendMessContact:
    method: POST
    url: /contact/sendMailContact
    bundle: frontend
    controller: HomeController
    action: sendMailContact

NewUserRegister:
    method: POST
    url: /user/new
    bundle: frontend
    controller: ActionsController
    action: registerUser

UserLogin:
    method: POST
    url: /user/login
    bundle: frontend
    controller: ActionsController
    action: loginUser

test:
    method: GET
    url: /home/index/{article_id}/{annee}
    bundle: frontend
    controller: HomeController
    action: index