### Inserer les routes ici ###
#### SITE BUNDLE #####

Home:
    method: GET
    url: /
    bundle: frontend
    controller: HomeController
    action: index

ArticlesList:
    method: GET
    url: /blog/article/all
    bundle: frontend
    controller: HomeController
    action: index

SendMessContact:
    method: POST
    url: /contact/sendMailContact
    bundle: frontend
    controller: HomeController
    action: sendMailContact